Source/OCMockTests/OCMArgTests.m
Added 4 tests to cover `[OCMArg resolveSpecialValues:...]`.
=> Added test coverage for OCMArg's `resolveSpecialValues` class method

Source/OCMock/OCMFunctions.m, Source/OCMockTests/OCMockObjectTests.m
There was a typo in the initialization of type2NameEnd when type2 was
fully opaque causing OCMEqualTypesAllowingOpaqueStructsInternal() to
fails even though the types had the same name.
Introduce unit tests to test that case, and to ensure that the function
is symmetrical for its two arguments.
=> Fix OCMEqualTypesAllowingOpaqueStructsInternal when type2 is opaque

Source/OCMock/NSInvocation+OCMAdditions.m
Switch to `strlcpy` since it is safer to use and remove `strcpy` since it is insecure (although I don't know why unit test code would try to manipulate the buffer, but better safe than sorry).
=> Fix for clang static analyzer issue CWE-119

Source/OCMock/OCMInvocationMatcher.m
Where `OCMInvocationMatcher` wasn't releasing the recorded invocation
=> Fix Issue 197

Source/OCMock/OCMBlockCaller.m, Source/OCMock/OCMConstraint.m, Source/OCMock/OCMFunctions.m, Source/OCMock/OCMIndirectReturnValueProvider.m, Source/OCMock/OCMLocation.m, Source/OCMock/OCMMacroState.m, Source/OCMock/OCMNotificationPoster.m, Source/OCMock/OCMPassByRefSetter.m, Source/OCMock/OCMReturnValueProvider.m, Source/OCMock/OCMVerifier.m, Source/OCMock/OCObserverMockObject.m, Source/OCMockTests/OCMConstraintTests.m
Fixing issues identified by [Infer](https://github.com/facebook/infer)
```
OCMock/OCMBlockCaller.m:25: error: NULL_DEREFERENCE
pointer self last assigned on line 24 could be null and is dereferenced at line 25, column 2
OCMock/OCMConstraint.m:149: warning: IVAR_NOT_NULL_CHECKED
Instance variable self -> block is not checked for null, there could be a null pointer dereference: pointer self->block last accessed on line 149 could be null and is dereferenced at line 149, column 9
OCMock/OCMIndirectReturnValueProvider.m:27: error: NULL_DEREFERENCE
pointer self last assigned on line 26 could be null and is dereferenced at line 27, column 2
OCMock/OCMLocation.m:29: error: NULL_DEREFERENCE
pointer self last assigned on line 28 could be null and is dereferenced at line 29, column 5 …
```
=> Fix issues identified by Infer

Source/OCMock iOS/Info.plist, Source/OCMock.xcodeproj/project.pbxproj, Source/OCMock.xcodeproj/xcshareddata/xcschemes/OCMock iOS.xcscheme
Hey Erik,
I added an iOS Framework target. With that OCMock is Carthage compatible. You can learn more about Carthage [here](https://github.com/carthage/carthage#supporting-carthage-for-your-framework).
Additionally Carthage can also download releases from GitHub. You can see an example in [my fork](https://github.com/nerdishbynature/ocmock/releases/tag/v3.1.2).
=> Add iOS framework target

.travis.yml, Makefile
Updating the TravisCI configuration. This does the following:
- Builds on OS X Yosemite instead of Mavericks
- Builds using Xcode 6.4 instead of Xcode 6.1
- Tests 32-bit & 64-bit iOS builds
- Allows code using nullability annotations (introduced in Xcode 6.3) to be built on Travis
- Makes it easier to switch to Xcode 7 once available
=> Update Travis configuration to use latest Xcode

Source/OCMock/OCMockObject.m
=> Fixes typo in OCMockObject method name

Source/OCMock/OCMFunctions.h, Source/OCMock/OCMStubRecorder.h
See http://stackoverflow.com/questions/32503134/change-to-andreturn-breaks-c-compilation.
Perform runtime check of value as objc object is compatible with C++ compilation. Static is not.
=> Runtime check of andReturn() value type rather than static

Source/OCMock/OCMLocation.h
As detailed in #238, linking tests sometimes fails when OCMock is being used in Objective-C++ (.mm) test case files.
This commit solves that problem by conditionally declaring `OCMMakeLocation` as `extern "C"` when included in a C++ compilation unit, therefore fixing #238.
=> Fix linking in Objective–C++ tests.

Source/OCMock.xcodeproj/project.pbxproj, Source/OCMock/OCMStubRecorder.h
Turn on the "Defines Module" [DEFINES_MODULE] build setting in the OCMock target.
Fix imports in OCMStubRecorder.h which requires OCMFunctions.h to be a public header.
=> Add module support for the OS X framework.

Source/OCMock.xcodeproj/project.pbxproj
Something weird happened and OCMFunctionsPrivate.h got put into the Resources build phase instead of Headers which was causing it to be mastered into the frameworks.
=> OCMFunctionsPrivate.h is being mastered into the framework.

Source/OCMock/OCClassMockObject.m
isKindOfClass: is actually an instance method on NSObject (or other root classes).  It only works on class objects because all NSObject instance methods are inherited -- basically, a class object is an instance of whatever its root class is (if you look at a metaClass' isa pointer, it is always NSObject or its respective root class).  This means that calling -isKindOfClass: on class objects has often-unexpected behavior -- it only returns YES if NSObject is the argument, instead of implementing it from a class hierarchy perspective.  For checking inheritance with classes, the +isSubclassOfClass: method is provided, so I changed several places to use that instead.
=> Fix isKindOfClass on class objects

Source/OCMock/OCClassMockObject.m, Source/OCMock/OCMFunctions.m, Source/OCMock/OCMFunctionsPrivate.h
Removed direct usages of isa pointer.  That is a bad idea these days because of tagged pointers -- the raw pointer values may not be valid Class objects.  They were only used to manipulate meta classes though and those may have been OK.  However, object_getClass and object_setClass works just fine for them... at least, the unit tests still pass after I made the changes.
If there was some other reason to be directly changing the isa pointers I'm not aware of, ignore this pull request -- but it's a dangerous thing to be doing now.  object_setClass() goes through some runtime stuff now which may eventually be more important.
=> Remove direct isa pointer manipulation

Source/OCMock.xcodeproj/project.pbxproj
Noticed that this header is missing from the OCMockLib target. (`OCMFunctionsPrivate.h`)
It shouldn't matter, but the pbxproj nazi inside me insisted on sending this PR.
Please note that `OCMBoxedReturnValueProviderTests` changes are done automatically by Xcode. There should be no asset tag on these files anyway, so I feel like the change is for better.
=> Add missing private header in OCMockLib.

Source/OCMock/OCMObserverRecorder.h, Source/OCMock/OCMObserverRecorder.m, Source/OCMock/OCObserverMockObject.h, Source/OCMock/OCObserverMockObject.m
OCMObserverRecorder.h and OCObserverMockObject.h are not public headers, so the only headers available that describe the ```notificationWithName:object:``` method are in NSNotification.h. The methods described in NSNotification.h returns an NSNotification object, and since those have a return value, ARC adds an implicit retain when making calls like  ```[[someObserverMock expect] notificationWithName:@"some name" object:someObj]```. If you run a test that has code like this with Xcode's address sanitizer enabled, asan sees this as an issue and then attempts to break and notify you about it. In doing this, it goes to get some debug info about the return value of this method call and ends up de-referencing a nil pointer which crashes the test with EXC_BAD_ACCESS.
There are a few solutions …
=> Fixed asan crashing when using notificationWithName:object: in an ARC project

Source/OCMockTests/OCMockObjectTests.m
Replace -hasSuffix: which doesn't allow a nil argument with -uppercaseStringWithLocale: which does.
=> Fix unit test warnings.

OCMock.podspec, Source/OCMock.xcodeproj/project.pbxproj, Source/OCMock.xcodeproj/xcshareddata/xcschemes/OCMock tvOS.xcscheme, Tools/build.rb
- Based on existing `OCMock iOS` target aka dynamic framework
- Relies on the same Info.plist as any other Framework
- Same product name
- Same everything else
- Biggest difference - it has `appletvos` set as the base SDK, which is going to work only when building with Xcode 7.1 (any beta)
I don't think there is a need to add static library support, simply due:
- tvOS supports dynamic frameworks since day 1
- Frameworks have built-in module support, which is much better approach compared to prefix headers or C-style imports.
Should somewhat address #257.
=> Add basic tvOS support with new target and via CocoaPods.

Source/OCMock/OCMockObject.m, Source/OCMockTests/OCMockObjectTests.m
Currently OCMockObject checks if expectations fulfilled with increasing interval steps. This causes OCMock to wait more than given verification delay because current code does not check if next step interval is greater than remaining interval. 
PR contains the fix and a test case for it. You can verify the problem via reverting the change and running the test case.
=> Fix verifyWithDelay interval precision

Source/OCMock.xcodeproj/project.pbxproj
Remove all of the search path settings, they aren't necessary and are now causing warnings in OCMockLib.
=> Fix Xcode 7.2 warnings.

Source/OCMock/OCMPassByRefSetter.m, Source/OCMockTests/OCMockObjectTests.m
OCMock 3.2.1 introduced a bug where something like this crashes.
OCMStub([mockFileManager createSymbolicLinkAtURL:OCMOCK_ANY withDestinationURL:OCMOCK_ANY error:[OCMArg setTo:nil]]).andReturn(YES);
[mockFileManager createSymbolicLinkAtURL:symlinkFile withDestinationURL:symlinkDestination error:NULL];
Fix it by checking for NULL in OCMPassByRefSetter.
=> +[OCMArg setTo:] crashes if invoked with NULL

Source/OCMock.xcodeproj/project.pbxproj, Source/OCMock/NSInvocation+OCMAdditions.h, Source/OCMock/NSInvocation+OCMAdditions.m, Source/OCMock/OCMFunctions.m, Source/OCMock/OCMFunctionsPrivate.h, Source/OCMock/OCMInvocationMatcher.m, Source/OCMock/OCMMacroState.m, Source/OCMock/OCMock.h, Source/OCMock/OCMockObject.m, Source/OCMock/OCObserverMockObject.m, Source/OCMock/OCPartialMockObject.m, Source/OCMockTests/OCMockObjectPartialMocksTests.m, Source/OCMockTests/TestClassWithCustomReferenceCounting.h, Source/OCMockTests/TestClassWithCustomReferenceCounting.m
Make OCMockObject thread safe.
Synchronize on the four mutable array instance variables during access to ensure their consistency.
Retain everything retrieved from the arrays if the retrieved objects ever get used outside of the synchronized chunks.
Retain captured invocation arguments since the arguments could otherwise be deallocated at any time. The invocation can't outright retain its arguments since that would cause a retain cycle, so use a customized method to retain arguments that filters out self.
Add all the reference counting methods (-retainCount, -retain, -release, -autorelease) to OCPartialMockObject's selector black list. They're a recipe for stack overflow since partial mocks set up a forwarder for -retain. The forwarder would capture the call to -retain as an NSInvocation, …
=> OCMockObject is not thread safe

Source/Changes.txt, Source/OCMock/OCMMacroState.h, Source/OCMock/OCMMacroState.m, Source/OCMock/OCMock.h, Source/OCMockTests/OCMockObjectMacroTests.m
Added macro OCMReject that works similar to OCMStub and OCMExpect. It was missing for a long time. It is a lot easier to read.
I've seen in the documentation that it should be added after further quantifiers are added but it haven't been done in over a year so I thought that it would be useful to add this modern syntax with current functionality.
=> Added modern syntax for reject

Source/OCMock.xcodeproj/xcshareddata/xcbaselines/03565A3018F0566E003AE91E.xcbaseline/AB0B7B4B-6B80-4328-BA16-64F0AC33ED0D.plist, Source/OCMock.xcodeproj/xcshareddata/xcbaselines/03565A3018F0566E003AE91E.xcbaseline/Info.plist, Source/OCMock/OCMockObject.m, Source/OCMockTests/OCMockObjectTests.m
Without that fix, a test using both async verification & rejections
would wait for the whole given delay.
Performance test to confirm the problem & verify the fix included.
I also included baselines for the mentioned performance test.
I tried to write a regression test to verify that rejections do indeed work (i.e. throw) during async verification, like that:
```
- (void)testRejectsInvocationDuringAsynchronousVerification
{
OCMockObject *localMock = [OCMockObject niceMockForClass:[TestClassWithProperty class]];
[[localMock reject] title];
[[localMock expect] setTitle:OCMOCK_ANY];
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(0.01 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
[(id) localMock title];
});
@try {
[localMock verifyWithDelay:1];
} @catch(NSException *exception)  { …
```
=> Ignore rejection expectations during async verification

Source/OCMockTests/OCMockObjectRuntimeTests.m
The test asserts that calling `-init` throws -- its result is willfully ignored. Add pragma to instruct the compiler to ignore the warning in this case.
=> [Tests] Ignore unused result warning in test

Source/OCMockTests/OCMockObjectRuntimeTests.m
The test verifies that the two lines of code do not crash; the variables are written to but never read. Add pragma to instruct the compiler to ignore the warning in this case.
=> [Tests] Ignore unused variable warning in test

Source/OCMock.xcodeproj/project.pbxproj, Source/OCMock/OCPartialMockObject.m, Source/OCMockTests/OCMockObjectPartialMocksTests.m, Source/OCMockTests/Resources/TestObjects.xcdatamodeld/TestObjects.xcdatamodel/contents
@kyleve originally created https://github.com/erikdoe/ocmock/pull/181, I took the feedback that was incorporated in that PR and replayed his changes on top of the latest.
=> Allow mocking managed objects.

Source/OCMock/OCClassMockObject.m
It was generating documentation warning:
> OCClassMockObject.m:237:3: 
> '@interface' command should not be used in a comment attached to a non-interface declaration
=> Fix "'@interface' command should not be used in a comment attached to a non-interface declaration"

Source/OCMock/NSInvocation+OCMAdditions.m
The function object_isClass is only available starting from macOS
10.10 and iOS 8.0 SDKs. To allow targeting older systems (i.e. if
the deployment target is older), add an alternate implementation.
The implementation is based on the one used by the Swift runtime:
https://github.com/apple/swift/pull/11467/commits/0475307c08
Fixes issue #344.
=> Allow compilation with old deployment targets.

Source/OCMock/OCMFunctions.m, Source/OCMockTests/OCMBoxedReturnValueProviderTests.m
When building with iOS 11 SDK and running on iOS 10 device, the type
representation, some of structure type are incompatible and are not
considered equal even though they are.
This fixes the comparison by:
1.  properly parsing nested subtypes like {Foo={Bar={B}}}
2.  considering that a struct without a name {} is equal to any struct
3.  not use NSGetSizeAndAlignment to parse subtype like {__rep}
Fixes issue #342.
=> Fix comparison of struct type representation.

Source/OCMock/NSInvocation+OCMAdditions.m, Source/OCMockTests/OCMockObjectTests.m
This aims to resolve https://github.com/erikdoe/ocmock/issues/329.
I have added two new tests for `invokeBlockWithArgs`:
- The test for Protocol mocks crashes without this patch
- The test for Class mocks is for completeness, and does not require this patch
=> Fixed invokeBlockWithArgs crash when given protocol mocks

Source/OCMock/OCClassMockObject.m, Source/OCMockTests/OCMockObjectClassMethodMockingTests.m
Previously that first dynamically created subclass was kept around forever,
and if accessed somehow (for example by enumerating objc_getClassList) would
always raise NSInternalInconsistencyException.
=> When a second mock is created for the same class, dispose of the dynamically created subclass for the first mock.

Source/OCMock/NSInvocation+OCMAdditions.m, Source/OCMock/OCMFunctions.m, Source/OCMock/OCMFunctionsPrivate.h, Source/OCMockTests/OCMockObjectTests.m
The arguments passed to the recorder for a method-parameter of type `Class` were not retained, which can cause crashes if they are deallocated before they are used for verification.
As `Class` types are treated with as objects in ObjC, we should just retain them in the same way.
=> Retain class type arguments in NSInvocation

Source/OCMock/OCMock.h
If you enable `-wstrict-selector-matching` in your unit tests you'll get
many errors with OCMock mock objects since they will be of type `id` and
any selector that is referenced must be unique across all types in order
to avoid this error.
Given this is a pretty fundamental aspect of how mocks and OCMock work,
I believe silencing errors here is the right strategy vs disabling this
warning entirely for unit test code.
=> Silence strict selector matching warning

Source/OCMock.xcodeproj/project.pbxproj
This fixes command line warnings when running xcodebuild
```
The iOS Simulator deployment target is set to 5.0, but the range of supported deployment target versions for this platform is 8.0 to 12.2.99. (in target 'OCMockLib')
Mapping architecture arm64 to x86_64. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'OCMockLib')
Mapping architecture armv7 to i386. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in target 'OCMockLib')
Mapping architecture armv7s to i386. Ensure that this target's Architectures and Valid Architectures build settings are configured correctly for the iOS Simulator platform. (in …
```
=> Add valid archs for simulator to OCMocklib to silent xcodebuild warnings

Source/OCMock/OCMockObject.m, Source/OCMockTests/OCMockObjectClassMethodMockingTests.m, Source/OCMockTests/OCMockObjectPartialMocksTests.m, Source/OCMockTests/OCMockObjectProtocolMocksTests.m, Source/OCMockTests/OCMockObjectTests.m
OCMockObject invocations need to retain their arguments, however that can introduce retain cycles that wouldn't otherwise be there. It also makes dealloc tests fail for objects that get sent as arguments to mocks.
Break the chain in -stopMocking by emptying out the invocations.
https://github.com/erikdoe/ocmock/issues/307
=> OCMockObject invocations retain arguments

Source/OCMock/OCMReturnValueProvider.h, Source/OCMock/OCMReturnValueProvider.m, Source/OCMock/OCMStubRecorder.m, Source/OCMockTests/OCMockObjectTests.m
Fixing issue: https://github.com/erikdoe/ocmock/issues/356
In current commit there are: example of the #365 issue and its solution.
When returned object is the same as the mocked object for stub - do not invoke retain.
Mocked-object's lifetime is always longer than stub-object’s, therefore we do not worry that stub-object will be freed earlier than mocked-object(aka returned object).
Co-Authored-By: QB <victoriaqb@users.noreply.github.com>
=> Avoid retaining return value if it is the mock itself

Source/OCMock/OCMMacroState.m, Source/OCMock/OCMObserverRecorder.m, Source/OCMock/OCMRecorder.h, Source/OCMock/OCMRecorder.m, Source/OCMockTests/OCMockObjectMacroTests.m
Exception raises when OCMStub/OCMReject/OCMExpect used only to mocked object, so we added a flag isEverInvoked to check if the mock exists instead the using a real object. 
If YES - the needed chain of the mocking process raises, if NO - exception “OCMStub/OCMReject/OCMExpect must be used only to mocked object.” Raises to make you understand what goes wrong.
When you uses OCMStub/OCMReject/OCMExpect  on a real object in a test - your test doesn’t check anything and is always green. You must use mocks in the test (class / partial). In this case, the correct code check is performed.
Local and CI successful builds and xctests over the new code.
OCMStub/OCMReject/OCMExpect must be used only to mocked object.
Co-Authored-By: QB victoriaqb@users.noreply.github.com
=> Avoid a macros misuse

Source/OCMock/OCMockObject.m, Source/OCMockTests/OCMockObjectInternalTests.m, Source/OCMockTests/OCMockObjectVerifyAfterRunTests.m
This resolves #380 
Before:
```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '** Cannot handle or verify invocations. This error usually occurs when a mock object is used after stopMocking has been called on it. In most cases it is not necessary to call stopMocking. If you know you have to, please make sure that the mock object is not used afterwards.'
```
After:
```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '** Cannot handle or verify invocations on OCMockObject(CLLocationManager). This error usually occurs when a mock object is used after stopMocking has been called on it. In most cases it is not necessary to call stopMocking. If you know you have to, please make sure that the mock object is not …
```
=> Show description when throwing exceptions because of no invocations

Source/OCMock/OCMock.h
In cases where people are doing things like
NSBundle *foo = OCClassMock([NSBundle class])
or
id<MyProtocol> bar = OCClassMock([MyClass class])
calling OCMVerifyAll or OCMVerifyAllWithDelay requires a cast to (OCMockObject *) so that the verify methods can be found. This makes it so callers don't have to constantly do OCMVerifyAll((id)bar) or something similar.
=> Cast mock arguments in OCMVerify* macros

Source/OCMock/OCMStubRecorder.m, Source/OCMockTests/OCMockObjectTests.m
Previous code would only catch references to self when using the OCMStub/OCMExpect macros.
Now we avoid self referential retain loops if you use the `[[[foo stub] andReturn:foo] sharedInstance]` API.
=> Catches references to self when not using macros.

Source/OCMock/OCClassMockObject.m, Source/OCMock/OCObserverMockObject.m, Source/OCMock/OCProtocolMockObject.m, Source/OCMockTests/OCMockObjectPartialMocksTests.m, Source/OCMockTests/OCMockObjectProtocolMocksTests.m, Source/OCMockTests/OCMockObjectTests.m
Make descriptions match the object type they are describing.
Descriptions previously often had a bad class name.
=> Clean up descriptions

Source/OCMock/OCPartialMockObject.m
[super dealloc] was already calling stopMocking and stopMocking was setting realObject to nil, so this code is unneeded.
=> Remove unneeded dealloc from OCPartialMockObject

Source/OCMockTests/OCMockObjectTests.m
Right now there is a chance that the async code will run while another test is executing.
This allows the expectation to complete before starting another test.
=> Allow expectation to complete in test

Source/OCMock/OCMMacroState.m, Source/OCMockTests/OCMockObjectMacroTests.m
The exception message provided when attempting to mock an NSObject method (like hash)
with a macro is confusing. The updated text is much clearer as to possible causes.
=> Better exception when attempting to mock NSObject method with macro.

Source/OCMock/OCClassMockObject.m, Source/OCMockTests/OCMockObjectRuntimeTests.m
=> Blacklists `resolveClassMethod:` from having a forwarder set up for it.

Source/OCMock/OCMMacroState.h, Source/OCMock/OCMMacroState.m, Source/OCMock/OCMVerifier.m, Source/OCMock/OCMock.h, Source/OCMockTests/OCMockObjectMacroTests.m
If an exception was thrown in a `OCMExpect/OCMStub/OCMVerify` macro it would often
get replaced by a confusing error message in the `@finally` blocks of the macro.
Now the original exception is passed through.
As part of this discovered that `OCMVerifier` did not block having init called on it
twice like `OCMStubRecorder`.
=> Pass exceptions through macros

Source/OCMock/OCMockObject.m, Source/OCMockTests/OCMockObjectPartialMocksTests.m
Fix for #408.
The error message is now:
`Selector '%@' can not be verified using OCMVerify(). Use OCMExpect() instead.`
=> Better error message for OCMVerify of some methods on partial mocks.

Source/OCMock/OCClassMockObject.h, Source/OCMock/OCClassMockObject.m, Source/OCMockTests/OCMockObjectClassMethodMockingTests.m, Source/OCMockTests/OCMockObjectTests.m
Adding class methods after stopMocking was called could cause extremely confusing results
including crashes at runtime.
=> Add exception for mocking class methods after stopMocking called.

Source/OCMock.xcodeproj/project.pbxproj, Source/OCMock/NSInvocation+OCMAdditions.m, Source/OCMock/NSMethodSignature+OCMAdditions.m, Source/OCMock/OCMFunctions.m, Source/OCMock/OCMFunctionsPrivate.h, Source/OCMockTests/OCMNoEscapeBlockTests.m
Noescape blocks can be generated in certain conditions when using clang from source or if
you pass `-Xclang -fexperimental-optimized-noescape` to Xcode 11.
Essentially we don't want to copy these blocks because they exist only on the stack
and can't be moved to the heap. `copy` and `retain/release` are no-ops. Unfortunately
the lifetime of these blocks is tied to the stack they are in so if we attempt to retain
them beyond the lifetime of the stack they are declared in we will crash on release.
The test for this adds the `-Xclang -fexperimental-optimized-noescape` flags specifically
for the `OCMNoEscapeBlockTests.m` file and verifies that the blocks being generated are
noescape blocks and that OCMock can handle them.
This is for #417.
=> Add support for noescape blocks.

.travis.yml, Makefile
Update the Travis CI configuration to leverage the Xcode 11.5 environment. 
Upgrading from Xcode 11.2.1, here are the relevant release notes:
* [Xcode 11.3](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_3_release_notes)
* [Xcode 11.3.1](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_3_1_release_notes)
* [Xcode 11.4](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_4_release_notes)
* [Xcode 11.4.1](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_4_1_release_notes)
* [Xcode 11.5](https://developer.apple.com/documentation/xcode_release_notes/xcode_11_5_release_notes)
=> Update CI to Xcode 11.5

Source/OCMock/OCMVerifier.h, Source/OCMock/OCMVerifier.m
It's better to forward declare these instead of import them directly per general best practice :)
=> Use forward declaration in OCMVerifier.h

Examples/iPhoneExample/Classes/iPhoneExampleAppDelegate.h, Source/OCMock/OCMVerifier.h, Source/OCMockTests/OCMockObjectDynamicPropertyMockingTests.m, Source/OCMockTests/OCMockObjectInternalTests.m, Source/OCMockTests/OCMockObjectTests.m
The retain attributes can be replaced by `strong` for most of the time in ARC world. Since they were introduced 4-6 years ago, I think for now we can refresh these by using these new attributes which are more common. 
It shouldn't change anything drastically and the tests are still passing.
=> Replace retain attributes with other memory management attributes

Source/OCMock/OCClassMockObject.m, Source/OCMock/OCMMacroState.m, Source/OCMock/OCPartialMockObject.m, Source/OCMock/OCProtocolMockObject.m
Replace uses of NSAssert with real exceptions because various builds turn off asserts using NS_BLOCK_ASSERTIONS, but we still want bad state to fail tests.
=> Replace asserts with exceptions.

Source/OCMock/OCPartialMockObject.m
Top of tree clang supports `-Wmisleading-indentation` as a warning. It gets flagged
in one place in OCMock due to a mix of tabs and spaces. This fixes it by replacing one
tab with spaces.
=> Fix warning with `-Wmisleading-indentation`

Source/OCMock/OCMInvocationExpectation.m, Source/OCMockTests/OCMockObjectMacroTests.m
Throw an exception if invocationActions are added to a reject.
Refer to #434.
=> Disable invocation and arg actions for rejects.

Source/OCMock.xcodeproj/project.pbxproj, Source/OCMock/OCMBoxedReturnValueProvider.m, Source/OCMockTests/OCMBoxedReturnValueProviderTests.m, Source/OCMockTests/OCMCPlusPlus11Tests.mm, Source/OCMockTests/OCMCPlusPlus98Tests.mm, Source/OCMockTests/OCMockObjectMacroTests.m
Fix for #403.
This improves the special case handling of passing nil in return values to handle
C++ cases that previously weren't working.
Adds tests for C++11 and C++98 variants. To test fully tests need to be executed in both
32bit and 64 bit modes.
=> Handle using nil as argument for andReturn in ObjC++ code.

Source/OCMock/OCMNonRetainingObjectReturnValueProvider.m
Retain the returnValues so they aren't released between the time they are returned
and the time they are either retained by the caller, or in the case of non ARC calling
code possibly not retained at all because the receiver was expecting a retained value.
=> Retain returnValues

Source/OCMock/NSInvocation+OCMAdditions.m, Source/OCMockTests/NSInvocationOCMAdditionsTests.m
Invocation descriptions had trouble dealing with `[OCM anyPointer]`
=> Add support for `[OCM anyPointer]` to invocation descriptions

Source/OCMock/OCMBoxedReturnValueProvider.m
The code was using the method signature's return type to determine how large a stack buffer should be used for retrieving the overridden return value. This was problematic as the overridden return value may not be of the same type as the method signature's return type. It may be an unrelated type, in the case where `-handleInvocation:` would go on to throw an exception, or it may be a related type of a different size. This comes up when dealing with methods of a `BOOL` return type but overriding the return value with an integer literal (`0`/`1`) or C11 boolean constant (`true`/`false`) which are of type `int` and so require more than a single byte to store.
To address this we now use a size derived from the overridden return value's Objective-C type encoding to determine how
large a …
=> Fix a stack overflow within -[OCMBoxedReturnValueProvider handleInvocation:]

Source/OCMock/OCMockMacros.h
@throw generating clang-tidy warnings with `google-objc-avoid-throwing-exception`
https://clang.llvm.org/extra/clang-tidy/checks/google-objc-avoid-throwing-exception.html
https://clang.llvm.org/extra/clang-tidy/#suppressing-undesired-diagnostics
=> Turn off unwanted clang-tidy warnings

Source/OCMock.xcodeproj/project.pbxproj, Source/OCMock/NSInvocation+OCMAdditions.m, Source/OCMock/OCMFunctions.m, Source/OCMock/OCMFunctionsPrivate.h, Source/OCMockTests/OCMFunctionsTests.m, Source/OCMockTests/OCMockObjectTests.m
In some cases OCMArgActions and/or OCMConstraints are passed as "blocks".
We need to retain those actions/blocks in our invocation matchers.
Fix for #458.
=> Retain objects passed as block arguments.

Source/OCMock/OCMockObject.m, Source/OCMockTests/OCMockObjectTests.m
Prevents users from accidentally instantiating an OCMockObject.
=> Block direct instantiation of OCMockObject

Source/OCMock/NSInvocation+OCMAdditions.h, Source/OCMock/NSInvocation+OCMAdditions.m, Source/OCMock/OCMInvocationStub.m, Source/OCMock/OCMNonRetainingObjectReturnValueProvider.m, Source/OCMock/OCMRealObjectForwarder.m, Source/OCMockTests/OCMockObjectRuntimeTests.m
Case where a value is being returned as part of an andDo or other invocation actions.
Given that invocation actions can be chained, we need to make sure to only affect
the final action in the chain.
RealObjectForwarders are treated specially because their implementations will handle
the case correctly, so we need to balance out the retainCounts.
=> Fix up create family method retain counts in cases other than just andReturn

Source/OCMock.xcodeproj/project.pbxproj, Source/OCMock/OCMStubRecorder.h, Source/OCMock/OCMStubRecorder.m, Source/OCMockTests/OCMockObjectMacroTests.m
Suggested implementation for #420
=> Add support for .andFulfill(expectation)

Source/OCMock/NSInvocation+OCMAdditions.m
We should never have a return value set in `retainObjectArgumentsExcludingObject` so remove the untested code block that is there, and throw an exception if someehow we end up in this unexpected state.
=> Remove unused code in retainObjectArgumentsExcludingObject

Source/OCMock/OCClassMockObject.h, Source/OCMock/OCClassMockObject.m, Source/OCMock/OCPartialMockObject.m, Source/OCMockTests/OCMockObjectTests.m
Certain classes should not be mocked. They may not be able to support being mocked
because of implementation details that conflict with how OCMock is implemented.
This allows library developers to prevent those classes from being mocked.
=> Add support for classes blocking mocking.

Source/OCMock/OCMStubRecorder.h
Adds a `.andDebugger` and `.andLog` to stubs and expectations to make them easier to debug.
=> Add support for debugging/logging

Source/OCMock/NSNotificationCenter+OCMAdditions.m, Source/OCMock/OCMockObject.h, Source/OCMock/OCObserverMockObject.h, Source/OCMock/OCObserverMockObject.m, Source/OCMockTests/OCMockObjectMacroTests.m, Source/OCMockTests/OCObserverMockObjectTests.m
AFAICT XCTNSNotificationExpectations can fulfill all the requirements of
OCMObserverMockObjects, so let's set ourselves up so we can remove the cruft.
Fix for #463 463
=> Deprecate OCMObserverMockObjects

Source/OCMock/OCPartialMockObject.m
Creating a partial mock of an object that has KVO registrations was silently disabling the KVO notifications. This could lead to very confusing situations for the user. 
Emit a warning about creating partial mocks of objects with KVO registrations to try and make clear what the problem is.
=> Add warning message regarding KVO notifications not being sent

Source/OCMock/NSObject+OCMAdditions.m
This is cleaner version of getting the forwarder rather than depending on a (hopefully) non-existent selector.
=> Move to using _objc_msgForward directly

Source/OCMockTests/OCMockObjectTests.m
This shadow variable `mock` is from `testBlockConstraintRetainedByStub`.
The `mock` is already defined as a private variable in the `@implementation` section.
With `-Wshadow` and `-Werror` this became an error so we should fix this.
=> Remove unnecessary shadow variable

Source/OCMockTests/OCMockObjectMacroTests.m
The `expectedFile` is actually a suffix of `reportedFile` on my local run. The test started failing with the equality check.
Switch to check if it's a suffix resolves the issue.
=> Check expected file path as a suffix in OCMockObjectMacroTests

Source/OCMock/NSInvocation+OCMAdditions.m
NSGetSizeAndAlignment is horribly documented IMHO. The alignp argument is the alignment of the type, not the aligned size of the type. On a 64 bit system this just "happens" to work for many types that aren't structs.
=> Fix up usage of NSGetSizeAndAlignment

Source/OCMock/OCMFunctions.m, Source/OCMockTests/OCMFunctionsTests.m
Ran into some interesting cases where `byref` was not returning the expected values
and `OCMTypeWithoutQualifiers` was running into issues and was actually returning the
next type in a string.
=> `byref` sometimes just returns 'R' as encoding

Source/OCMock/OCMockObject.m, Source/OCMockTests/OCMockObjectMacroTests.m
This allows a mock to be created inside an OCM Macro call while still preserving the case where we don't support mocking init.
Suggested fix for #449
=> Allow mocks to be created inside OCM Macro calls

Source/OCMock/OCPartialMockObject.m, Source/OCMockTests/OCMockObjectPartialMocksTests.m, Source/OCMockTests/OCMockObjectTests.m
If you manage to pass a proxy into OCMPartialMock it crashes quite quickly, so let's just prevent it from happening at all.
Also test that you can class mock a proxy.
=> Enforce that you cannot partial mock a proxy.

Source/OCMock/OCMMacroState.h
https://releases.llvm.org/12.0.0/tools/clang/docs/DiagnosticsReference.html#woverriding-method-mismatch
=> Fix up with -Woverriding-method-mismatch

Makefile
After these changes OCMock framework can be linked with Mac Catalyst apps and used for testing
Test Plan:
`make dist`
verify that Build/ocmock-3.9.1.dmg/OCMock.xcframework/Info.plist
contains a library with:
identifier: ios-arm64_x86_64-maccatalyst
supported arcs: arm64, x86_64
SupportedPlatformVariant: maccatalyst
=> Include Mac Catalyst architecture when making a dist framework

OCMock.podspec
Xcode 14.3 does not support building for a minimum macOS target of 10.10.
More context at https://stackoverflow.com/questions/75574268/missing-file-libarclite-iphoneos-a-xcode-14-3
=> Fix Xcode 14.3 build issue

Source/OCMock/OCPartialMockObject.m, Source/OCMockTests/OCMCPlusPlus11Tests.mm, Source/OCMockTests/OCMCPlusPlus98Tests.mm
For `OCMPartialMock()` objects, forwarding the `.cxx_destruct` method can in certain cases cause use-after-free and timing errors. The use case that triggers this behavior sits firmly as an edge case but is still easy enough to stumble into that it's worth fixing.
To trigger this issue, partially mock a derived class. This derived class can not have any ivars that would generate `.cxx_*` methods. A parent of the derived class must include at least one ivar that causes `.cxx_*` method generation.
```
@interface BaseFake : NSObject {
std::map<int, int> mapper_;
}
@end
@interface DerivedFake : BaseFake
@end
```
[-[OCPartialMockObject prepareObjectForInstanceMethodMocking]](https://github.com/erikdoe/ocmock/blob/558881746ccb4597cafd73a73e5689d2c092c5a3/Source/OCMock/OCPartialMockObject.m#L154) …
=> partial mock: skip forwarding of .cxx_* methods

Source/OCMock/OCMArg.m, Source/OCMock/OCMPassByRefSetter.h, Source/OCMock/OCMPassByRefSetter.m
This fixes up a crash that was found in Chrome when running on an iOS 15 device.
It did not show up on the simulator.
https://chromium-review.googlesource.com/c/chromium/src/+/3011651
Calling `object_getClass` on something that isn't an object is at best undefined
behavior.
=> Fix up crash when calling object_getClass on non object.

OCMock.podspec
With the release of [CocoaPods v1.13.0](https://github.com/CocoaPods/CocoaPods/releases/tag/1.13.0), visionOS support was introduced.
=> Add visionos platform support to podspec

Source/OCMock/NSObject+OCMAdditions.m
=> Fix Xcode 15.3 build error on Intel Macs
